version: "3.9"

services:
  dash_app:
    build: .
    container_name: dash_app
    ports:
      - "8888:8050"
    volumes:
      - .:/app # optional: for live code updates
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python app.py
